name: Reusable · NOP

on:
  merge_group:
  pull_request_target:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  nop:
    name: nop
    runs-on: ubuntu-latest
    steps:
      - name: Confirm execution
        run: echo "NOP workflow executed successfully. DUMMY_VAR=${DUMMY_VAR}"
