name: Reusable · NOP

on:
  merge_group:
  pull_request_target:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  nop:
    name: nop
    runs-on: ubuntu-latest
    steps:
      - name: Handle sherlock DUMMY_VAR
        if: ${{ contains(vars.DUMMY_VAR, 'sherlock') }}
        env:
          DUMMY_VAR: ${{ vars.DUMMY_VAR }}
        run: echo "NOP workflow executed successfully. DUMMY_VAR contains sherlock: ${DUMMY_VAR}"

      - name: Handle non-sherlock DUMMY_VAR
        if: ${{ !contains(vars.DUMMY_VAR, 'sherlock') }}
        env:
          DUMMY_VAR: ${{ vars.DUMMY_VAR }}
        run: echo "NOP workflow executed successfully. DUMMY_VAR does not contain sherlock: ${DUMMY_VAR}"
